### ISSUE TITLE
Image replacement code

### ISSUE THREAD

**Issue by cfjedimaster** [zaccolley/letterboxd#34]
I'm using a bit of your code in a different project (https://www.raymondcamden.com/2020/08/04/sharing-your-movies-with-pipedream-and-letterboxd), and I've noticed that the code to return different sizes isn't working correctly. It tries to replace this, `'-0-150-0-225-crop`, but in my testing, I'm seeing an image URL like with this: `0-500-0-750-crop`. The code doesn't throw an error, it just ends up returning the same URLs for each of the sizes.

**Comment by zaccolley** [comment]
Thanks @cfjedimaster I'll have a look!
