### ISSUE TITLE
API use

### ISSUE THREAD

**Issue by webbuildlucas** [zaccolley/letterboxd#42]
Hello,

In your Readme.md you stated that you would use the api when it's out there.
I noticed that there's an api on http://api-docs.letterboxd.com/. Is the api not functional yet or are you planning to add it soon?

**Comment by zaccolley** [comment]
Ooh interesting, I figured that it wasn't public facing because of this: https://letterboxd.com/api-beta/

Will have a look

**Comment by zaccolley** [comment]
Yeah looks like you need to sign requests with an API key which for most people they wont have because the API isn't public yet
